"""Refatoração Pedido

Revision ID: 074f06f47542
Revises: 3baebe7c2751
Create Date: 2023-12-19 09:48:50.527163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '074f06f47542'
down_revision: Union[str, None] = '3baebe7c2751'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('observacoes', sa.String(), nullable=True))
        batch_op.drop_column('observacao')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('observacao', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('observacoes')

    # ### end Alembic commands ###
