"""Refatoração Pedido

Revision ID: 2cef1388c4e4
Revises: ae1e8fb34b32
Create Date: 2023-12-19 09:20:09.905866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cef1388c4e4'
down_revision: Union[str, None] = 'ae1e8fb34b32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('local_entrega', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('tipo_entrega', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('observacao', sa.String(), nullable=True))
        batch_op.drop_column('observacoes')
        batch_op.drop_column('endereco')
        batch_op.drop_column('entrega')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entrega', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('endereco', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('observacoes', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('observacao')
        batch_op.drop_column('tipo_entrega')
        batch_op.drop_column('local_entrega')

    # ### end Alembic commands ###
